src/student/dto/schedules.dto.ts
src/student/student.controller.ts
src/student/student.service.ts

Na rota `GET /student/schedules`:
- Adiciona paginação.
- Adiciona nome do monitor e estudante aos eventos retornados.
- Adiciona query param `status` para filtrar eventos pelo ID do status.
- Adiciona query param `eventType` para filtrar eventos em que o usuário é monitor ou estudante.

BACK-87: Add pagination and user name

---

src/app.module.ts

Conserta o path dos templates de e-mail para apontar à pasta certa: `/dist/email/templates`.

fix: Conserta path dos templates de e-mail

---

src/common/dto/query-pagination.dto.ts
src/monitor/commands/list-monitors.command.ts
src/monitor/dto/list-monitors.request.dto.ts
src/monitor/monitor.controller.ts
src/monitor/monitor.module.ts
src/monitor/monitor.service.ts
src/monitor/utils/monitor.enum.ts

- Recebe o campo status como parâmetro na rota `GET /monitor/all`.
- Pagina resultado na rota direto no banco.
- Extrai método de listar monitorias para usar o padrão command.

fix: Filtra monitores por status e pagina no banco

---

src/schedules/domain/schedule.ts
src/schedules/utils/schedule.factory.ts
src/student/commands/schedule-monitoring.command.ts
src/student/dto/schedule-monitoring.dto.ts
src/student/student.controller.ts
src/student/utils/exceptions.ts
src/subject/domain/subject.ts

Ao criar um agendamento não estão sendo feitas validações corretas encima dos horários disponíveis do monitor e dos agendamentos confirmados que ele já possui.
Considerando que o horários disponível do monitor 11 é todos os dias das 09:00 até as 14:00 e que o único agendamento confirmado dele começa em `2023-03-26 09:00:00` e termina em `2023-03-26 10:00:00`, faça requisições para a rota `POST /student/{monitor_id}/schedule` variando as datas de início e fim para validar se:

fix: Verifica disponibilidade de monitor ao agendar

---

src/student/commands/schedule-monitoring.command.ts
src/student/student.controller.ts
src/student/utils/exceptions.ts

Ao criar um agendamento não estão sendo feitas validações corretas encima dos horários disponíveis do aluno e dos agendamentos confirmados ou pendentes que ele já possui.
```json
{
"statusCode": 412,
"message": "Aluno já possui um agendamento com status 'Aguardando aprovação do monitor' no horário solicitado",
"error": "Precondition Failed"
}
```

fix: Checa agendamentos do aluno ao agendar

---

src/teacher/teacher.service.ts

Antes, não era possível assinalar um professor a uma matéria se esse mesmo registro já estivesse no banco. Com o novo status de responsabilidade finalizada, agora é possível reassinalar um professor a uma matéria que ele já tenha ministrado anteriormente, considerando que esta responsabilidade já esteja com status 3 (Finalizada).

fix: Possibilita reassinalar professor se a matéria já foi finalizada.

---

Dockerfile
package.json

O deploy em stg não tá funcionando porque ao buildar a imagem dá erro porque o husky não é instalado. 
- O husky só é instalado em dev, aí quando vai fazer deploy ele não é instalado e dá erro porque o npm tenta rodar ele.
- Verifica se ao rodar husky vai dar erro de módulo não encontrado, pois se der, ignora.

fix: Não roda husky quando instalar com ci

---

prisma/migrations/20230505235325_add_schedule_description/migration.sql
prisma/schema.prisma
src/email/email.service.ts
src/schedules/domain/schedule.ts
src/schedules/utils/schedule.factory.ts
src/schedules/utils/select-schedule.prisma-sql.ts
src/student/commands/schedule-monitoring.command.ts
src/student/dto/schedule-monitoring.dto.ts

[📌 Receber campo description na rota de agendamento](https://computero.atlassian.net/jira/software/projects/DS/boards/8?selectedIssue=DS-116)
- Adiciona o campo descrição na tabela ScheduleMonitoring;
- Altera a rota /student/{monitor_id}/schedule para receber o campo description; (O campo pode ser opcional);
- Tratamento de erro caso o campo seja diferente de string ou que exceda o tamanho 500;
- Altera a rota /schedules para receber o campo descrição;
(insert into student (user_id, description, enrollment, course_id, contact_email)
values
(6, '', '11111111', '1', 'marcos.aluno@icomp.ufam.edu.br')); 
(insert into monitor (id_status, responsible_professor_id, student_id, subject_id)
values
(1, 1, 6, 3));

feat: Add schedule description

---

src/user/commands/reset-password.command.ts
src/user/dto/reset-password.request.dto.ts
src/user/user.controller.ts
src/user/user.module.ts
src/user/utils/decoded-token.ts
src/user/utils/exceptions.ts

[📌 [DS-82] Cria rota para resetar senha](https://computero.atlassian.net/jira/software/projects/DS/boards/8?selectedIssue=DS-82)
Cria rota para resetar a senha de um usuario

feat: Cria rota para resetar a senha

---

src/user/commands/edit-user.command.ts
src/user/domain/coordinator.ts
src/user/domain/student.ts
src/user/domain/teacher.ts
src/user/dto/user-edit.dto.ts
src/user/user.controller.ts
src/user/user.module.ts
src/user/user.service.ts
src/user/utils/exceptions.ts
src/user/utils/user.factory.ts

[📌 Criar rota de editar dados de usuário](https://computero.atlassian.net/browse/DS-107)
Esta PR:
- Altera o arquivo userService para deixar de lançar exceções HTTP, deixando essa responsabilidade apenas no controlador;
- Altera o arquivo de exceções para tornar os erros de validação reutilizáveis (foram reutilizados na rota de edição);
- Adiciona a rota `PATCH /user` para editar dados do usuário logado;

feat: Adiciona rota de edição de usuários

---

src/main.ts

[📌 Não gerar swagger em produção](https://computero.atlassian.net/browse/DS-95)
Este commit altera o arquivo `main.ts` para gerar a documentação do swagger apenas nos casos onde a variávei `NODE_ENV` for diferente de 'production'. 
*OBS: Não esqueça de descartar as alterações no arquivo Makefile posteriomente. Elas são apenas para fins de teste.*

feat: Esconde swagger no ambiente de produção

---

src/monitor/commands/accept-schedule.command.ts
src/monitor/commands/refuse-scheduled-monitoring.command.ts
src/monitor/monitor.service.ts
src/student/commands/schedule-monitoring.command.ts

Esta PR corrige um bug onde rotas que acionavam notificações de e-mail estavam sendo retornadas sem o devido envio dos e-mails para os usuários. Foram adicionados os devidos `await` em todas as partes onde o envio de emails era necessário, para mitigar esse problema e garantir que o e-mail foi enviado antes do retorno da rota.

fix: Adiciona await aos envios de e-mail

---

src/schedules/commands/create-topic.command.ts
src/schedules/domain/schedule.ts
src/schedules/dto/create-topic.request.dto.ts
src/schedules/dto/topic.dto.ts
src/schedules/schedules.controller.ts
src/schedules/schedules.module.ts
src/schedules/utils/schedule-topic-formatter.ts

[📌 [DS-157] Criar rota para criar um novo assunto de agendamento](https://computero.atlassian.net/jira/software/projects/DS/boards/8?selectedIssue=DS-157)
Cria rota de criacao de topico

feat: Rota de criacao de topico

---

src/schedules/commands/get-topics.command.ts
src/schedules/domain/topic.ts
src/schedules/dto/get-topics.request.dto.ts
src/schedules/dto/get-topics.response.dto.ts
src/schedules/schedules.controller.ts
src/schedules/schedules.module.ts
src/schedules/utils/topic.fatory.ts
src/student/commands/schedule-monitoring.command.ts

[📌 Criar rota para buscar assuntos de agendamento](https://computero.atlassian.net/browse/DS-156)
Este PR: 
- Adiciona rota para listar assuntos de agendamento

feat: Adiciona rota de listar assuntos

---

src/user/commands/get-user-info.command.ts
src/user/dto/user-info.response.dto.ts

[📌 Rota de dados do usuário logado](https://computero.atlassian.net/jira/software/projects/DS/boards/8?selectedIssue=DS-131)
- Na rota de dados do usuário logado o atributo curso retorna um número: id do curso, é mais interessante retornar o nome do curso para evitar uma nova consulta. Foi alterado o atributo de resposta para o course_name

fix: Altera course_id para course_name

---

src/schedules/utils/schedule.factory.ts
src/schedules/utils/select-schedule.prisma-sql.ts
src/student/commands/list-student-schedules.command.ts
src/student/commands/schedule-monitoring.command.ts
src/student/dto/schedule-monitoring.dto.ts
src/student/student.controller.ts
src/student/utils/exceptions.ts

[📌 Alterar rota de agendamento para receber assunto](https://computero.atlassian.net/jira/software/projects/DS/boards/8?selectedIssue=DS-184)
- Adiciona o parâmetro topicId no body da rota de agendamento para salvo o assunto escolhido pelo aluno: /student/{monitor_id}/schedule
- Retorna o assunto do agendamento nas rotas que retornam agendamentos: /student/schedules
- Envia o assunto para o template de e-mail da notificação.

feat: Alterar rota de agendamento para receber assunto

---

Makefile
README.md

[📌 Consertar makefile para acessar banco](https://computero.atlassian.net/browse/DS-189)
Remove senha e nome do banco do comando `db-shell` no Makefile para permitir que ele possa ser executado em prod e staging.
- Estávamos passando a senha e o nome do banco de dev no comando `db-shell`, então quando tentamos rodar ele em stg ou prod não dá pra acessar o banco.
- Não passa mais a senha e o banco, deixa pro usuário colocar os dois de acordo com o ambiente

fix: Permite rodar make db-shell em todos os envs

---

src/student/commands/schedule-monitoring.command.ts
src/student/dto/schedule-monitoring.dto.ts

- O Assunto (topic) deveria ser um parâmetro opcional, da forma que estava implementada impedia que um agendamento fosse feito sem um topicID
- Esse parâmetro foi alterado para ser opcional. Foi adicionada uma lógica para verificar se um topicId foi passado para ser lançada a exceção de erro corretamente. A busca no banco só é feita caso o usuário passe um topicId

fix: Altera a rota de agendamento para o assunto ser opcional

---

src/utils/validations.ts

[📌 Remover validação de e-mail institucional](https://computero.atlassian.net/browse/DS-198)
Remove a validação de e-mail que permite que apenas e-mail com domínio icomp, super ou ufam se cadastrem no sistema.
```json
{
"email": "emailfake@emailfake.com.br",
"name": "Fernando neves",
"password": "12345678",
"confirm_password": "12345678",
"description": "",
"enrollment": "45645643",
"course_id": 1,
"contact_email": "",
"whatsapp": "",
"linkedin": ""
}
```

chore: Remove validação de e-mail institucional

---

src/user/commands/edit-user.command.ts

[📌 Criar rota de editar dados de usuário](https://computero.atlassian.net/browse/DS-107)
Este PR:
- Adiciona uma verificação extra no começo das validações para tratar strings vazias ou campos passados como **null**
O bug estava sendo gerado porque alguns campos quando estavam sendo passados como null, isto é, ocultos do body, geravam erro na request. 
Adicionada verificação adicional para checar se o campo é undefined antes de iniciar as validações

fix: Corrige rota de edição de usuários

---

src/subject/subject.service.ts

Retorna monitores aprovados e disponíveis por disciplina na rota `GET /subject`. Isso foi feito para que o front consiga verificar se o usuário logado possui uma monitoria com um desses status em alguma disciplina.

chore: Retorna monitores aprovados nas disciplinas

---

src/schedules/commands/list-ending-schedules.command.ts

[📌 Sistema exige que Monitor confirme realização de ajuda antes de passar da data limite do agendamento](https://computero.atlassian.net/browse/DS-203)
- Corrige o comando que busca os agendamentos que já deveriam ser finalizados, agora ele leva em consideração o horário de Manaus
- O fuso horário de Manaus não estava sendo considerado
- Subtraído o horário com base no fuso de Manaus.

fix: Corrige o fuso horário na busca de agendamentos não finalizados

---

Makefile
prisma/mocks/coordinator.mock.ts
prisma/mocks/monitors.mock.ts
prisma/mocks/schedules.mock.ts
prisma/mocks/students.mock.ts
prisma/mocks/teachers.mock.ts
prisma/populate.ts

[📌 Criar comando para popular banco  de dev](https://computero.atlassian.net/browse/DS-180)
Este PR: 
- Adiciona o script `populate.ts` para popular o banco de dados.
- Adiciona os comandos `make db-populate` e `make db-prune` ao Makefile. Este segundo serve para limpar todos os dados do docker e do banco local.

chore: Adiciona script para popular o banco

---

src/utils/validations.ts

[📌 Corrigir regex do linkedin](https://computero.atlassian.net/browse/DS-220)
Corrige regex de validação do linkedin
- A regex antiga não aceitava link sem `https` e outras coisas simples
- Usa reges do site https://www.debugpointer.com/regex/regex-for-linkedin-profile-url

fix: Conserta regex da entrada do linkedin

---

src/monitor/commands/get-monitor.command.ts
src/monitor/domain/monitor.ts
src/monitor/monitor.controller.ts
src/monitor/monitor.module.ts
src/monitor/utils/monitor.factory.ts

📌 [Criar rota de dados de monitoria](https://computero.atlassian.net/browse/DS-211)
Esta PR adiciona uma nova rota (`GET /monitor/:id`) para listar os dados de uma monitoria, bem como deprecia a rota `GET /availability/:monitorID`, uma vez que as informações de disponibilidades já ficarão atreladas ao monitor na nova rota.

feat: Nova rota para listar dados de monitor

---

prisma/schema.prisma

Remove vírgula errada no esquema do prisma. Tá causando erro no `npx prisma generate`

fix: Remove vírgula indevida

---

src/utils/validations.ts

O usuário com nome "Jo Pereira" não tá conseguindo se cadastrar porque a regex de validação do nome exige ao menos 3 letras nas palavras do nome passado.
Muda a regex para a do site https://www.regextester.com/93648

fix: Conserta regex do nome do usuário

---

src/utils/validations.ts

[📌 Ativar a validação de email](https://computero.atlassian.net/jira/software/projects/DS/boards/8?selectedIssue=DS-225)
Adiciona a validação de e-mail que permite que apenas e-mail com domínio icomp, super ou ufam se cadastrem no sistema.
```json
{
"email": "meuemail@icomp.ufam.com.br",
"name": "Fulano Tal",
"password": "12345678",
"confirm_password": "12345678",
"description": "",
"enrollment": "45645643",
"course_id": 1,
"contact_email": "",
"whatsapp": "",
"linkedin": ""
}
```

Revert "chore: Remove validação de e-mail institucional"

---

src/utils/validations.ts

[📌 Campo de e-mail não aceita hífen](https://computero.atlassian.net/browse/DS-229)
Essa PR adiciona hífen (-) ao Regex, que valida os E-mails, como caractere aceito.
- Adiciona o hífen (-) como caractere aceito aos e-mail utilizados para cadastro.
- Qual foi a causa do bug? E-mails com hífen (-) não estavam sendo aceitos no formulário de cadastro.
- O que foi feito para corrigi-lo? O caractere hífen (-) foi adicionado ao regex de validação de e-mails.

fix: Aceita emails com hifen

---

src/auth/auth.service.ts
src/auth/interfaces/jwt-user.interface.ts
src/user/user.service.ts

[📌 título do card](link-do-card)
Para mostrar ou não o botão de Monitoria na sidebar no front, precisamos retornar a monitoria ativa (status aprovada ou disponível) do aluno no token de autenticação, caso exista uma.

feat: Add monitoria ativa ao token se existir uma

---

src/monitor/commands/refuse-scheduled-monitoring.command.ts

[📌 Nome do Monitor na notificação de Cancelamento](https://computero.atlassian.net/jira/software/projects/DS/boards/8?selectedIssue=DS-261)
Esta PR adiciona o Nome do Monitor no E-mail de notificação de Cancelamento de solicitação de monitoria. 
- Qual foi a causa do bug? Quando o monitor recusava uma solicitação de monitoria o e-mail de notificação que é enviado para o Estudante apresentava o nome incorreto no campo `Monitor`.
- O que foi feito para corrigi-lo? O nome correto do monitor foi passado para o template de e-mail de cancelamento.

fix: nome do monitor na notificacao de cancelamento

---

src/enum-validator.validator.ts
src/subject/dto/subject-query.dto.ts
src/subject/subject.controller.ts
src/subject/subject.service.ts

[📌Alterar rota de disciplinas](https://computero.atlassian.net/jira/software/projects/DS/boards/8?selectedIssue=DS-239)
- Adiciona o parâmetro teacherId na rota GET /subject
- Adiciona o parâmetro monitorStatus na rota GET /subject
- Adiciona enrollment ao objeto student dentro de cada objeto da lista Monitor
AVAILABLE = 3,)

feat: altera rota disciplina

---

__tests__/__utils__/factories/student.prisma.factory.ts
__tests__/modules/student/commands/create-student.command.mock.ts
__tests__/modules/student/commands/create-student.command.spec.ts
__tests__/modules/student/commands/find-enrollment.command.mock.ts
__tests__/modules/student/commands/find-enrollment.command.spec.ts
__tests__/modules/student/commands/find-one-by-id.command.mock.ts
__tests__/modules/student/commands/find-one-by-id.command.spec.ts
__tests__/modules/student/commands/get-monitor-availability.command.mock.ts
__tests__/modules/student/commands/get-monitor-availability.command.spec.ts

[📌 Criar testes do módulo student](https://computero.atlassian.net/browse/DS-246)
- Configura execução dos testes com jest
- Centraliza testes na pasta `__tests__`
- Cria testes unitários do Módulo `student`
- Foi desenvolvido os testes unitários dos seguintes commands do módulo student:
- `create-student.command`
- `find-enrollment.command`
- `find-one-by-id.command`
- `get-monitor-availability.command`

test: Testes unitários do módulo 'student'

---

prisma/migrations/20230929000420_create_table_subject_enrollment/migration.sql
prisma/schema.prisma
src/enrollment/domain/enrollment.ts
src/subject/domain/subject.ts
src/subject/utils/subject.factory.ts
src/user/domain/student.ts

[📌 [DS-270] Salvar matrícula no banco](https://computero.atlassian.net/jira/software/projects/DS/boards/8?selectedIssue=DS-270)
- Cria tabela `subject_enrollment`
- Altera classes e factories para receber novo relacionamento

feat: Cria nova tabela subject_enrollment

---

src/subject/dto/subject-query.dto.ts
src/subject/subject.controller.ts
src/subject/subject.module.ts
src/subject/subject.service.ts
src/subject/utils/exceptions.ts

[📌 Rota de disciplinas matriculadas](https://computero.atlassian.net/browse/DS-272)
- Foi add o parâmetro boolean `onlyEnrollments` na rota `GET /subject` , caso seja setado com `true` a rota deve retornar somente as disciplinas que o Estudante logado estiver matriculado.
- Caso o parâmetro boolean `onlyEnrollments` seja setado com `true` e o usuário logado não seja um Estudante a rota `GET /subject` vai retornar `400 - usuário logado não é um aluno`
- Foi add o campo `isStudentEnrolled` às disciplinas retonadas pelas rotas `GET /subject` e `GET /subject/:id`, nas disciplinas que o Estudante logado estiver matriculado o campo `isStudentEnrolled`  estará com `true`,  caso não esteja matriculado esse campo estará com `false`.

feat: Rota de disciplinas matriculadas

---

src/subject/commands/cancel-subject-enrollment.command.ts
src/subject/commands/create-subject-enrollment.command.ts
src/subject/dto/enrollment.dto.ts
src/subject/subject.controller.ts
src/subject/subject.module.ts
src/subject/subject.service.ts
src/subject/utils/exceptions.ts

[📌 [DS-271] Criar rotas de matricular e desmatricular]((https://computero.atlassian.net/browse/DS-271))
- Cria rotas de matricular e desmatricular aluno

feat: Cria rota para cancelar e criar matricula

---

src/subject/subject.service.ts

[📌 Rota de disciplinas matriculadas](https://computero.atlassian.net/browse/DS-272)
- Qual foi a causa do bug? Ao realizar uma consulta no banco de dados na tabela `subject_enrrollment` não estava sendo considerado que o campo `canceled_at` também deve ser `null`
- O que foi feito para corrigi-lo? Na query de consulta do banco de dado foi adicionado na `where`  a clausula `canceled_at: null`

fix: Considerando o campo 'canceled_at'

---

src/subject/subject.service.ts

[📌 Rota de disciplinas matriculadas](https://computero.atlassian.net/browse/DS-272)
- Qual foi a causa do bug? O campo `canceled_at` não estava sendo consultado na tabela correta.
- O que foi feito para corrigi-lo? Na query de consulta a tabela `subject_enrollment` do banco de dado foi adicionado na `where`  a clausula `canceled_at: null`

fix: Consultando 'canceled_at' na tabela correta

---

src/subject/commands/cancel-subject-enrollment.command.ts
src/subject/commands/create-subject-enrollment.command.ts
src/subject/subject.controller.ts
src/subject/utils/exceptions.ts

[📌 Criar rotas de matricular e desmatricular](https://computero.atlassian.net/browse/DS-271)
Faz as seguintes correções nas rotas de matrícula
- Retorna 404 se for passado o ID de uma disciplina inexistente nas rotas de matrícula e desmatrícula
- Retorna 412 se o aluno tentar se matricular em uma disciplina em que tem monitoria aberta (status aguardando aprovação, disponível ou aprovada)

fix: Conserta regras nas rotas de matrícula

---

src/subject/subject.controller.ts
src/subject/subject.service.ts

- Manda mensagem de erro no retorno da rota de criar matrícula.
- Só retorna alunos com matrícula ativa na rota de detalhes de disciplina

fix: Manda mensagem de erro

---

src/auth/auth.service.ts
src/auth/interfaces/jwt-user.interface.ts
src/monitor/commands/end-monitoring.command.ts
src/monitor/monitor.controller.ts
src/monitor/monitor.service.ts
src/subject/commands/end-responsability-command.ts
src/subject/subject.controller.ts
src/teacher/commands/assign-subject.command.ts
src/teacher/dto/user-token.dto.ts
src/teacher/teacher.controller.ts
src/teacher/teacher.module.ts
src/teacher/utils/exceptions.ts
src/user/user.service.ts

[📌 Ajustar permissões de coordenadores](https://computero.atlassian.net/browse/DS-285)
- As rotas a seguir foram bloqueadas para, caso um coordenador esteja logado, somente consiga realizar alterações se pertencer ao mesmo departamento da Disciplina em questão.
- Rotas Bloqueadas:
`POST /teacher/assign-subject`
`PATCH /subject/responsability/{id}/end`
`PATCH /monitor/{id}/refuse`
`PATCH /monitor/{id}/accept`
`PATCH /monitor/{monitorId}/end`
`POST /teacher/assign-subject`
`PATCH /subject/responsability/{id}/end`
`PATCH /monitor/{id}/refuse`
`PATCH /monitor/{id}/accept`
`PATCH /monitor/{monitorId}/end`
**Código HTTP**: 401 - UNAUTHORIZED
**Menssagem de Erro**: Coordenador(a) não pertence ao Departamento da Disciplina.

feat: Bloquear Coordenador de outro departamento

---

docker-compose.yml

[📌 Consertar erro do parametro replicas ](https://computero.atlassian.net/browse/DS-243?atlOrigin=eyJpIjoiNmIxZTcyNDZmOTRlNGY2ZjlmYTQ2ZDVhNWNlZjcwNTEiLCJwIjoiaiJ9)
Altera o parametro replicas de instancias no docker-compose do backend. 
Ao subir a instancia no servidor o docker está lançando um warn de função deprecated.
Alteração no docker-ompose com o novo formato para subir instancia, sugerido pelo docker. 
Ao subir a aplicação, em stagin ou em produção o docker disparava um warn de função deprecated.

Concerta parametros com warn do docker

---

src/user/user.service.ts

A chamada da PrismaORM foi instanciada de forma errada, ocasionando em falha no momento do deploy.
[ ] Executar o build do backend.
[ ] O build deve ser feito sem falhas durante a compilação do prisma.

fix: Correção na chamada do prisma no módulo de usuario

---

src/auth/auth.service.ts
src/user/user.service.ts

- Adiciona informações de token caso o usuário seja professor.
- Usuário do tipo professor não conseguia aceitar/recusar monitores pois as informações de token não estavam sendo coletadas corretamente.
Adicionado funções para coletar essas informações.

fix: corrige permissao de professor para aceitar/recusar monitor

---

src/subject/subject.controller.ts
src/subject/subject.service.ts

- Adiciona uma nova rota que retornar todas as disciplinas sem nenhum tipo de paginação

feat: Criar rota que retorne todas as disciplinas sem nenhum tipo de paginação

---

src/monitor/monitor.service.ts

[📌 Remover restrição de Monitoria](https://computero.atlassian.net/browse/DS-313)
- Remover restrição de monitoria onde um aluno só pode ser monitor de apenas uma disciplina por vez no sistema

fix: Remover restrição de Monitoria
