ajuda-ai-ufam/backend

.dockerignore, Dockerfile, docker-compose.yml, src/user/user.controller.ts
=> AJD-X:Test docker

prisma/migrations/20221111035839_create_tables_monitor_and_schedule_monitoring/migration.sql, prisma/migrations/20221112035733_rename_monitor_table/migration.sql, prisma/schema.prisma, src/app.module.ts, src/monitor/dto/request-monitoring.dto.ts, src/monitor/monitor.controller.ts, src/monitor/monitor.module.ts, src/monitor/monitor.service.ts, src/student/student.module.ts, src/student/student.service.ts, src/subject/subject.service.ts, src/user/user.service.ts
- Nova tabela monitor
- Nova tabela schedule_monitoring
- Nova rota para solicitar monitoria
- Nova rota para buscar detalhes de monitor
=> BACK-37: Solicitar monitoria de disciplina

src/subject/subject.service.ts
Retorna nome, email e ID dos professores e monitores na rota de detalhes de disciplina.
=> feat: Retorna dados dos professores e monitores

src/subject/subject.service.ts
Retorna o curso do monitor na rota de detalhes de disciplina.
=> feat: Retorna dados do curso na rota de disciplina

env.example, src/email/email.service.ts, src/email/templates/schedule_cancel_recipient_confirmation.hbs, src/email/templates/schedule_cancel_sender_confirmation.hbs, src/schedules/commands/cancel-schedule.command.ts, src/schedules/schedules.controller.ts, src/schedules/schedules.module.ts, src/schedules/utils/exceptions.ts
Criação de uma nova rota na API para a funcionalidade de desmarcar agendamentos.
=> feat: Cria rota para desmarcar agendamentos

src/generate-code/generate-code.module.ts, src/monitor/monitor.module.ts, src/schedules/schedules.module.ts, src/student/commands/create-student.command.ts, src/student/commands/find-enrollment.command.ts, src/student/commands/find-one-by-id.command.ts, src/student/commands/get-monitor-availability.command.ts, src/student/commands/list-student-schedules.command.ts, src/student/commands/schedule-monitoring.command.ts, src/student/student.controller.ts, src/student/student.module.ts, src/user/user.module.ts, src/user/user.service.ts
Contém o fix referente à CR DS-56. Conferir no link abaixo: 
https://computero.atlassian.net/browse/DS-56?atlOrigin=eyJpIjoiMzQ1MzkwOGI0MTUwNDY3MjhlMjZmMmIzMTYxYjY2NDIiLCJwIjoiaiJ9
=> fix: Ajusta filtro de lista de agendamentos e refatora módulo de estudante para o padrão Command.

Makefile, docker-compose.dev.yml
- Adiciona comando para criar migrações no Makefile.
- Cria volume no docker-compose.dev para que o autoreload funcione em desenvolvimento.
=> build: Add volumes no docker-compose de dev

prisma/migrations/20230404222303_add_schedule_end_date/migration.sql, prisma/schema.prisma, prisma/seed.ts
This adds an `end_date` column to the `subject_responsability` table in the database.
=> feat: Add an ending date to subject_responsability table

src/subject/subject.service.ts
Retornar o ID da responsabilidade das rotas GET /subject e GET subject/:id
Acessar os Endpoint GET /subject e GET subject/:id e conferir se o ID retornado é o mesmo do banco.
=> Add id subject responsability endpoint

Makefile
=> fix: Remove @ do docker-compose

Makefile, src/subject/subject.service.ts
=> [Deploy] Staging

src/student/commands/list-student-schedules.command.ts
- Ao listar agendamentos de monitor do usuário logado pega apenas os agendamentos cuja monitoria ainda está disponível.
- Ao verificar apenas o agendamento do dia atual em diante, considera horário AMT.
=> fix: Checa apenas monitoria disponível

prisma/migrations/20230416015626_add_monitor_end_date/migration.sql, prisma/schema.prisma, src/subject/commands/end-responsability-command.ts, src/subject/subject.controller.ts, src/subject/subject.module.ts, src/subject/utils/exceptions.ts, src/subject/utils/subject.enum.ts
Cria a coluna `end_date` na tabela `monitor` para salvar a data em que uma determinada monitoria foi finalizada.
=> feat: Adiciona data de finalização de monitoria

src/subject/subject.controller.ts, src/subject/subject.service.ts
Retorna linkedin, e-mail de contato e whatsapp dos monitores na rota `GET /subjcet/:id`.
=> chore: Retorna dados de contato do monitor

src/monitor/commands/end-monitoring.command.ts, src/monitor/monitor.controller.ts, src/monitor/monitor.module.ts, src/monitor/utils/exceptions.ts, src/subject/utils/exceptions.ts
Implementação de uma nova rota no controlador de monitores para setar a monitoria com status 4 (Finalizada). Remoção de um import não utilizado nas exceptions do módulo subject.
=> feat: Adiciona rota de finalização de monitoria

src/utils/validations.ts
Esta rota muda o arquivo `validations.ts` para permitir os domínios `super.ufam.edu.br` e `ufam.edu.br`
Segue link do card: [DS-126](https://computero.atlassian.net/browse/DS-126?atlOrigin=eyJpIjoiY2ZkNDMzN2JlYzU3NGJhMWE4YmNiNzA4ZGY2MjRkNWYiLCJwIjoiaiJ9)
=> feat: Permite novos domínios de email durante a validação.

src/email/email.service.ts, src/email/templates/schedule_monitoring.hbs, src/monitor/commands/end-monitoring.command.ts, src/monitor/monitor.controller.ts, src/monitor/utils/exceptions.ts, src/student/commands/schedule-monitoring.command.ts, src/student/student.module.ts
Este commit adiciona o envio de uma notificação por e-mail toda vez que um agendamento é solicitado pelo aluno. 
Segue link do card: [DS-122](https://computero.atlassian.net/browse/DS-122?atlOrigin=eyJpIjoiOGU2YTM4YjkyMjczNGRmNjg3MDM2ODJjNTg2ODE2Y2MiLCJwIjoiaiJ9)
=> feat: Adiciona notificação de e-mail ao solicitar um agendamento

src/email/email.service.ts, src/email/templates/refused_scheduled_monitoring.hbs, src/monitor/commands/refuse-scheduled-monitoring.command.ts, src/monitor/monitor.controller.ts, src/monitor/monitor.module.ts, src/monitor/monitor.service.ts, src/monitor/utils/exceptions.ts
[📌 DS-124: Notificação de agendamento recusado](https://computero.atlassian.net/browse/DS-124?atlOrigin=eyJpIjoiZWRlMDU3YjRhYmJhNGU0YWFkZmM0ZjI1OTQxYjNkZjAiLCJwIjoiaiJ9)
Esta PR adiciona uma notificação por e-mail para o aluno, quando um monitor rejeita o agendamento solicitado. 
- Adicionado um novo template de e-mail na pasta de templates
- A rota `/monitor/refuse/scheduled-monitoring/{scheduled_monitoring_id}` foi refatorada para o padrão command
=> feat: Notifica por e-mail ao rejeitar agendamento

src/email/email.service.ts, src/user/commands/create-reset-password-token.command.ts, src/user/dto/reset-password-token.request.dto.ts, src/user/user.controller.ts, src/user/user.module.ts, src/user/utils/exceptions.ts, src/user/utils/jwt-recover.interface.ts, src/user/utils/verification-code.enum.ts
[📌 Gerar código para resetar senha](https://computero.atlassian.net/jira/software/projects/DS/boards/8?selectedIssue=DS-80)
Cria a rota de recuperação de senha
=> feat:  Criar rota de recuperação de senha

src/email/templates/email_reset_password_token.hbs
=> fix: Adiciona handlebar

src/user/commands/create-reset-password-token.command.ts, src/user/user.controller.ts, src/user/utils/exceptions.ts
Remove regra de usuário precisa ser validado para esquecer a senha
=> fix: Remove regra de usuário validado

src/monitor/commands/end-monitoring.command.ts, src/student/commands/list-student-schedules.command.ts
[📌 [BACK] Monitor removido perde acesso aos seus agendamentos antigos com Alunos](https://computero.atlassian.net/browse/DS-130?atlOrigin=eyJpIjoiZmYxMTE0Y2NjNDcwNDc0ZmJiYmM2NDY0MjRiNGRjMjQiLCJwIjoiaiJ9)
Este commit altera a listagem de agendamentos. Agora, é possível visualizar os horários agendados em monitorias ativas e finalizadas.
Também foi alterada a rota de finalizar monitoria, para cancelar automaticamente todos os agendamentos pendentes e/ou confirmados uma vez que o aluno é removido da monitoria.
- Causa do bug
a cláusula where não listava as monitorias passadas do aluno. ao finalizar monitoria, não estava se encerrando os agendamentos pendentes.
alterada a classe de `list-student-schedules.command.ts` para mostrar também agendamentos de …
=> fix: Mostra agendamentos de monitorias encerradas

src/email/email.service.ts, src/email/templates/accepted_scheduled_monitoring.hbs, src/monitor/commands/accept-schedule.command.ts, src/monitor/commands/refuse-scheduled-monitoring.command.ts
[📌 Notificação de agendamento confirmado](https://computero.atlassian.net/jira/software/projects/DS/boards/8?selectedIssue=DS-123)
Esta PR adiciona uma nova notificação via e-mail, enviada para o aluno quando um monitor aceita sua solicitação de agendamento.
Pré-condições:
- Ter acesso a uma conta de estudante
- Ter acesso a uma conta de monitor ativo
- Ter acesso ao e-mail da conta de estudante
Passo-a-passo
=> feat: Notifica por e-mail ao aceitar agendamento

src/auth/auth.service.ts, src/email/templates/accept_monitor.hbs, src/email/templates/accepted_scheduled_monitoring.hbs, src/email/templates/refuse_monitor.hbs, src/email/templates/request_monitor.hbs, src/email/templates/schedule_monitoring.hbs, src/generate-code/generate-code.service.ts, src/monitor/monitor.service.ts, src/monitor/utils/exceptions.ts, src/student/utils/exceptions.ts, src/subject/utils/exceptions.ts, src/teacher/teacher.service.ts, src/teacher/utils/exceptions.ts, src/user/user.service.ts, src/user/utils/exceptions.ts
Trata a mensagem de retorno das rotas em relação ao genêro
=> fix: Trata genero dos retornos das rotas

.gitignore, package-lock.json, package.json, prisma/seed.ts
[📌 Inserir professores no banco de produção](https://computero.atlassian.net/jira/software/projects/DS/boards/8?selectedIssue=DS-120)
Cria o template de CSV com professores e coordenadores e os insere no banco de dados.
- Alterar o arquivo seed.ts para inserir os novos usuários, já validados;
- Atualiza os usuários do CSV para o tipo professor;
- Vincula as matérias dos professores que foram predefinidas de acordo com a planilha repassada
- Atualiza os usuários do CSV para o tipo Coordenador;
Verificar se os usuários foram inseridos corretamente, com o seu perfil pré-definido.
No caso de professores, verificar se estão vinculados com suas matérias (subject_responsability)
=> feat: Criação de template e script para inserção de professores

src/email/templates/accept_monitor.hbs, src/email/templates/refuse_monitor.hbs, src/email/templates/refused_scheduled_monitoring.hbs
[📌 [BACK] Alterar links dos e-mails para apontar à tela /login](https://computero.atlassian.net/browse/DS-149)
Altera o nome da tela de login no frontend de `/` para `/login` de acordo com a PR:
- https://github.com/ajuda-ai-ufam/frontend/pull/121
=> chore: Altera o nome da tela de login

src/user/commands/create-reset-password-token.command.ts
Ajusta forma de como eh verificado se um token esta expirado
- A forma como estavamos verificando se um token esta expirado estava invalida logicamente
- Implementacao da forma correta logica de verificar se um token esta expirado ou nao
=> fix: Ajusta forma de verificacao

src/user/user.controller.ts
Adiciona o retorno da excecao de codigo usado
=> fix: Adiciona retorno para erro de codigo usado

src/user/commands/get-user-info.command.ts, src/user/dto/user-info.response.dto.ts, src/user/user.controller.ts, src/user/user.module.ts
[📌 Rota de dados do usuário logado](https://computero.atlassian.net/jira/software/projects/DS/boards/8?selectedIssue=DS-131)
Adiciona a rota  /user/me que retorna os dados cadastrais do usuário logado
=> feat: Adiciona rota de dados do usuário logado 

src/email/email.service.ts, src/email/templates/accept_monitor.hbs, src/monitor/monitor.service.ts
[📌 Direcionamento do link e-mail "Solicitação para ser monitor foi aceita"](https://computero.atlassian.net/jira/software/projects/DS/boards/8?selectedIssue=DS-160)
- Altera o template de email de solicitação aceita.
Pré-condições:
- Ter acesso a uma conta de estudante
- Ter acesso ao e-mail da conta de estudante
- Ter acesso a uma conta de Coordenador.
=> feat: Adiciona link de redicionamento no email de "Solicitação para ser monitor foi aceita"

src/user/user.module.ts
Remove jwtservice dos providers do modulo de usuario
- Retorna erro 500 na rota de reset-password/token do usuario
- Para corrigir foi necessario apenas remover o jwtservice dos providers do usuario
=> fix: Remove jwtservice dos providers

Makefile, prisma/migrations/20230603180021_create_table_schedule_topics/migration.sql, prisma/schema.prisma
[📌 Cria tabela de assunto e relacionar a agendamento](https://computero.atlassian.net/jira/software/projects/DS/boards/8?selectedIssue=DS-155)
Cria tabela de assunto no banco e faz os relacionamentos necessarios
=> feat: Cria tabela de assunto e relacoes

src/user/commands/create-reset-password-token.command.ts, src/user/utils/jwt-recover.interface.ts
Adiciona o nome do usuário no token de atualização de senha para que o front consiga verificar se a senha nova possui o nome do usuário antes de fazer a requisição.
=> feat: Add nome do usuario no token de reset-pass

src/email/templates/schedule_monitoring.hbs, src/student/commands/schedule-monitoring.command.ts
[📌 Alterar template de notificação de agendamento criado](https://computero.atlassian.net/jira/software/projects/DS/boards/8?selectedIssue=DS-159)
- Altera o template de email para aceitar os parâmetros: Topic e Description
=> feat: Altera o template de notificação de agendamento criado

src/user/commands/edit-user.command.ts, src/user/dto/user-edit.dto.ts, src/utils/validations.ts
[📌 Criar rota de editar dados de usuário](https://computero.atlassian.net/browse/DS-107)
Esta PR: 
- Altera a condição de validação dos campos 
- Conserta o problema de campos vazios estarem sendo inseridos no banco ao fazer requests com strings de tamanho 0.
O bug estava sendo causado pois as validações não estavam sido feitas quando os campos eram strings vazias, já que as condições eram, por exemplo, `if (!data.password)`. Esta condição faz com que o JS entenda que, mesmo em casos onde o password não seja undefined, a condição seja falsa também para strings vazias, arrays vazios, etc.
Para contornar esse bug, foi explicitamente adicionado ao código que a validação deve ser executada em todos os casos onde o campo é …
=> fix: Valida campos vazios no back

src/subject/subject.service.ts
[📌 Ordenar Tela de Disciplinas por ordem Alfabética](https://computero.atlassian.net/jira/software/projects/DS/boards/8?selectedIssue=DS-190)
- Altera a rota /subject para listar as disciplinas em ordem alfabética
=> refactor: Altera a rota disciplinas por ordem Alfabética

src/schedules/utils/schedule-topic-formatter.ts
[📌 [DS-207] Tópico com "_" passa o caracter normalmente para o token](https://computero.atlassian.net/browse/DS-207)
Altera o formatador de topico para retirar "_" do token
=> fix: Retira "_" dos tokens

.dockerignore, Makefile, docker-compose.dev.yml, docker-compose.yml
Corrige a instalação de libs no repositório que não instala no container.
=> build: Corrige instalação de libs no container

.infra/apache2.config
- Add `RewriteEngine On` para permitir que URLs possam ser acessadas diretamente
- Remove `/` ao fim do ProxyPass porque tava colocando // na req e não dava pra acessar rota nenhuma.
=> fix: Add RewriteEngine e remove / indevida

prisma/migrations/20230712020117_create_table_monitor_settings/migration.sql, prisma/schema.prisma
[📌Criar tabela com configurações de monitoria](https://computero.atlassian.net/jira/software/projects/DS/boards/8?selectedIssue=DS-209)
- Adiciona a tabela monitor_settings
- Adiciona nova coluna em schedule_monitoring para receber o monitor_setting id
=> feat: Cria tabela monitor_settings

src/email/email.service.ts, src/email/templates/accepted_scheduled_monitoring.hbs, src/email/templates/refused_scheduled_monitoring.hbs, src/monitor/commands/accept-schedule.command.ts, src/monitor/commands/refuse-scheduled-monitoring.command.ts, src/monitor/monitor.controller.ts
[📌 Add preferência de atendimento nas notificações por e-mail](https://computero.atlassian.net/browse/DS-213)
Esta PR adiciona o campo `preferential_place` às notificações de agendamento recusado / confirmado.
=> feat: Adiciona local de monitoria aos emails

src/utils/validations.ts
Corrige regex para aceitar acentuações
=> fix: Conserta regex do nome para acentos

.infra/system_start.sh, Makefile
[📌 Criar script para subir back ao ligar a máquina na UFAM](https://computero.atlassian.net/browse/DS-260)
- Cria arquivo com comandos para subir o sistema em produção sempre que a máquina inicializar.
- Cria comando make para subir o backend em produção sem baixar código do github
- Cria comandos para verificar o status e reiniciar o serviço que sobe o sistema em produção em iniciar máquina.
=> build: Cria bash para reiniciar sistema em prod

src/enrollment/domain/enrollment.ts
- Ajusta tipagem do dominio enrollment para se adequar ao prisma
=> fix: Ajusta tipagem de acordo com schema

src/monitor/monitor.service.ts, src/student/commands/schedule-monitoring.command.ts, src/student/student.controller.ts, src/student/utils/exceptions.ts
[📌 Regra de agendamento só com matrícula](https://computero.atlassian.net/jira/software/projects/DS/boards/8?selectedIssue=DS-273)
- Altera a rota POST /student/{monitor_id}/schedule para agendar somente caso o aluno esteja matriculado na disciplina
- Alteração a rota POST /monitor/request para solicitar somente caso o aluno não esteja matriculado na disciplina
- Possuir um monitor disponível na disciplina que será testada (subject_id)
- Possuir na tabela subject_enrollment um item com conta de estudante que será testada (student id) e que tenha relação com uma disciplina (subject_id). (Para solicitações bem sucedidas)
=> feat: Altera rota de agendamento e monitor com regra de matrícula

prisma/migrations/20231105015350_create_table_department/migration.sql, prisma/migrations/20231105020412_create_table_super_coordinators/migration.sql, prisma/schema.prisma
[📌 Criar tabelas de instituto e super user](https://computero.atlassian.net/jira/software/projects/DS/boards/8?selectedIssue=DS-283)
- Cria a tabela departments
- Cria a tabela super_coordinators
=> feat: Cria tabelas department e super_coordinators

prisma/migrations/20231108230004_add_siape_column_teacher_table/migration.sql, prisma/mocks/teachers.mock.ts, prisma/populate.ts, prisma/schema.prisma, prisma/seed.ts, src/teacher/teacher.service.ts, src/user/dto/teacher-create.dto.ts, src/user/user.service.ts, src/user/utils/exceptions.ts, src/utils/validations.ts
[📌 Criar coluna SIAPE dos professores](https://computero.atlassian.net/browse/DS-288)
- Foi add uma nova coluna `siape` na tabela `Teacher`, esse novo campo não é obrigatório
=> feat: Criar coluna SIAPE dos professores

src/auth/enums/type-user.enum.ts, src/monitor/commands/end-monitoring.command.ts, src/monitor/monitor.controller.ts, src/monitor/monitor.service.ts, src/schedules/schedules.controller.ts, src/subject/subject.controller.ts, src/teacher/teacher.controller.ts
[📌Adicionar permissão de super coordenador](https://computero.atlassian.net/jira/software/projects/DS/boards/8?selectedIssue=DS-287)
- Adiciona o type_user 4 - Super Coordenador no Banco de dados
- Altera as rotas abaixo para permitir que usuários do tipo Super Coordenador (type 4) tenha as mesmas permissões de Professor
```
POST /teacher/assign-subject
PATCH /subject/responsability/{id}/end
PATCH /monitor/{id}/refuse
PATCH /monitor/{id}/accept
PATCH /monitor/{monitorId}/end
GET /schedules
```
=> feat: Adiciona permissao super coordenador

prisma/migrations/20240201040841_create_table_external_monitoring/migration.sql, prisma/schema.prisma
[📌Criar nova tabela](https://computero.atlassian.net/browse/DS-314)
- Cria a tabela external-monitoring
=> feat: Cria tabela external-monitoring

src/email/email.service.ts, src/email/templates/external-monitoring.hbs, src/monitor/commands/create-externalMonitoring.command.ts, src/monitor/dto/external-monitoring.dto.ts, src/monitor/monitor.controller.ts, src/monitor/monitor.module.ts, src/monitor/monitor.service.ts, src/monitor/utils/exceptions.ts
[📌 título do card](link-do-card)
- Alteração 1
- Alteração 2
=> Rota external monitorig

src/student/commands/find-all-students.command.ts, src/student/student.controller.ts
[📌 título do card](link-do-card)
- Alteração 1
- Alteração 2
=> fix: retira paginação da rota student

prisma/seed.ts, src/schedules/utils/schedules.enum.ts
[📌Atualizar Rota do Agendamento - Aluno/Monitor](https://computero.atlassian.net/browse/DS-325)
- Adiciona um novo status para a rota de agendamento (Realizado Externamente)
=> feat: Atualizar Rota do Agendamento - Aluno/Monitor

src/schedules/commands/list-external-monitoring.command.ts, src/schedules/schedules.controller.ts, src/schedules/schedules.module.ts, src/schedules/utils/schedule.factory.ts, src/schedules/utils/select-schedule-external.prisma.sql.ts
[📌 título do card](link-do-card)
- Alteração 1
- Alteração 2
=> feat: adiciona nova rota para filtra monitoria externa
